Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,1 +1,43 @@
+name: Deploy Sileo Repo
 
+on:
+  push:
+    branches:
+      - main  # 监听 main 分支上的变化
+    paths:
+      - 'debs/**'  # 监听 debs 目录下的文件变化
+
+jobs:
+  build:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v2
+
+    - name: Install dpkg-scanpackages
+      run: sudo apt-get update && sudo apt-get install -y dpkg-dev
+
+    - name: Ensure script has execute permissions
+      run: chmod +x ./generate_packages.sh
+
+    - name: Run generate_packages.sh
+      run: bash ./generate_packages.sh
+
+    - name: Commit and push updated Packages
+      env:
+        GITHUB_TOKEN: ${{ secrets.PAT }}  # 使用新的个人访问令牌
+      run: |
+        git config --global user.name "github-actions[bot]"
+        git config --global user.email "github-actions[bot]@users.noreply.github.com"
+        git pull origin main  # 拉取远程更改
+        git add Packages Packages.bz2 Packages.gz Release
+        git commit -m "Update Packages files" || echo "No changes to commit"
+        git push origin main || echo "Push failed"
+
+    - name: Deploy to GitHub Pages
+      uses: peaceiris/actions-gh-pages@v3
+      with:
+        personal_token: ${{ secrets.PAT }}  # 使用新的个人访问令牌
+        publish_branch: gh-pages
+        publish_dir: ./  # 确保你希望发布的内容在仓库根目录下
